"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, RotateCcw } from "lucide-react";
import { alertService } from "@/services";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { SeverityBadge } from "@/components/shared/severity-badge";
import { StatusBadge } from "@/components/shared/status-badge";
import { PageError, PageLoading, PageEmpty } from "@/components/shared/page-states";
import { Pagination } from "@/components/shared/pagination";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { timeAgo, severityColor } from "@/lib/utils";
import { Progress } from "@/components/ui/progress";

const SEVERITIES = ["critical", "high", "medium", "low"];
const STATUSES = ["open", "investigating", "resolved", "false_positive"];

export default function AlertsPage() {
  const queryClient = useQueryClient();
  const [severity, setSeverity] = useState("all");
  const [status, setStatus] = useState("open");
  const [page, setPage] = useState(1);

  const params = useMemo(
    () => ({
      severity: severity === "all" ? undefined : severity,
      status,
      page,
      page_size: 25,
    }),
    [severity, status, page],
  );

  const { data, isLoading, isError, error, refetch } = useQuery({
    queryKey: ["alerts", params],
    queryFn: () => alertService.list(params),
  });

  return (
    <div>
      <PageHeader
        title="Alerts"
        description="Detected threats generated by detection rules and correlation engine."
        actions={
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              void refetch();
              void queryClient.invalidateQueries({ queryKey: ["alerts"] });
            }}
          >
            <RotateCcw className="h-3.5 w-3.5" />
            Refresh
          </Button>
        }
      />

      <div className="mb-4 flex flex-wrap items-center gap-2 rounded-md border border-border bg-surface p-3">
        <BellRing className="h-4 w-4 text-muted" />
        <Select value={severity} onValueChange={(v) => { setSeverity(v); setPage(1); }}>
          <SelectTrigger className="w-40">
            <SelectValue placeholder="Severity" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All severities</SelectItem>
            {SEVERITIES.map((s) => (
              <SelectItem key={s} value={s}>{s}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={status} onValueChange={(v) => { setStatus(v); setPage(1); }}>
          <SelectTrigger className="w-44">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            {STATUSES.map((s) => (
              <SelectItem key={s} value={s}>{s.replace("_", " ")}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {isLoading && <PageLoading rows={15} />}
      {isError && <PageError message={(error as Error)?.message} onRetry={() => refetch()} />}
      {data && data.items.length === 0 && <PageEmpty title="No alerts in this view" />}

      {data && data.items.length > 0 && (
        <>
          <div className="rounded-md border border-border bg-surface">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Alert</TableHead>
                  <TableHead>Severity</TableHead>
                  <TableHead>Host / Source</TableHead>
                  <TableHead>Events</TableHead>
                  <TableHead>Risk</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Last Seen</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data.items.map((alert) => {
                  const sc = severityColor(alert.severity);
                  return (
                    <TableRow key={alert.id}>
                      <TableCell className="max-w-[320px]">
                        <Link href={`/alerts/detail?id=${alert.alert_id}`} className="hover:text-accent">
                          <span className="block truncate text-[13px] font-medium text-foreground">{alert.title}</span>
                          <span className="block font-mono text-[10px] text-muted">{alert.rule_id ?? "correlation"} · {alert.alert_id}</span>
                        </Link>
                      </TableCell>
                      <TableCell><SeverityBadge severity={alert.severity} className="text-[9px]" /></TableCell>
                      <TableCell>
                        <span className="block font-mono text-[11px] text-foreground">{alert.hostname ?? "—"}</span>
                        <span className="block font-mono text-[10px] text-muted">{alert.source_ip ?? ""}{alert.username ? ` · ${alert.username}` : ""}</span>
                      </TableCell>
                      <TableCell className="font-mono text-xs">{alert.event_count}</TableCell>
                      <TableCell className="w-32">
                        <div className="flex items-center gap-2">
                          <Progress value={alert.risk_score} colorClass={sc.dot} className="h-1 flex-1" />
                          <span className="font-mono text-[10px] text-muted">{alert.risk_score}</span>
                        </div>
                      </TableCell>
                      <TableCell><StatusBadge status={alert.status} className="text-[9px]" /></TableCell>
                      <TableCell className="whitespace-nowrap text-[11px] text-muted">{timeAgo(alert.last_seen)}</TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
          <Pagination page={page} totalPages={data.meta.total_pages} total={data.meta.total} onChange={setPage} />
        </>
      )}
    </div>
  );
}
